### ISSUE TITLE
We should support per-domain 404, 500 pages

### ISSUE THREAD

**Issue by kenperkins** [deconst/presenter#109]

**Comment by kenperkins** [comment]
![image](https://cloud.githubusercontent.com/assets/730664/14006056/7cf419da-f126-11e5-822a-a999dc40011e.png)

**Comment by smashwilson** [comment]
Yeah, these should definitely be rendering, but [they aren't](https://developer.rackspace.com/fooasdf/). I must have broken something. I'll have a look.

**Comment by smashwilson** [comment]
Grrr. I'm still seeing this.

**Comment by smashwilson** [comment]
Alright - _that_ should do it. Please re-open this if you see it again. This is one of those annoying bugs that's hard to verify if it's actually gone.

**Comment by kenperkins** [comment]
What was it in the end?

**Comment by smashwilson** [comment]
The details are all here: #111.
