### ISSUE TITLE
Report 404s instead of 500s

### ISSUE THREAD

**Issue by rgbkrk** [deconst/presenter#37]
It's static content. If it doesn't exist, it doesn't exist. This will also be important for any CDNs standing in front of it.

Originally reported in https://github.com/deconst/deconst-docs/issues/71

**Comment by smashwilson** [comment]
Moved to deconst-docs :point_right:

**Comment by smashwilson** [comment]
And now I disable issues for this repo, so you can _never click this link again._ Mwahahahahaha
