### ISSUE TITLE
How to get a right-aligned image to not be overlapped with code example?

### ISSUE THREAD

**Issue by annegentle** [deconst/presenter#99]
Any ideas how to fix this presentation problem? See attached screenshot.
<img width="823" alt="screen shot 2016-03-03 at 10 06 34 am" src="https://cloud.githubusercontent.com/assets/501981/13500420/0f10789a-e128-11e5-9a33-c3293c2ed565.png">

**Comment by ktbartholomew** [comment]
Moved to https://github.com/rackerlabs/nexus-control/issues/357
